// Follows tutorial from: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder


// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace StopSignDetectionTest
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            StopSignDetectionModel.ModelInput sampleData = new StopSignDetectionModel.ModelInput()
            {
                ImageSource = @"C:\StopSignImages\yannis-h-Sqez8_QTi8o-unsplash.jpg",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = StopSignDetectionModel.Predict(sampleData);



            Console.WriteLine($"ImageSource: {@"C:\StopSignImages\yannis-h-Sqez8_QTi8o-unsplash.jpg"}");


            Console.WriteLine("\n\nPredicted Boxes:\n");
            Console.WriteLine(predictionResult);
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();

            //var sw = new Stopwatch();
            //var files = Directory.GetFiles(@"C:/StopSignImages/", "*.jpg");

            //foreach (var file in files)
            //{
            //    sw.Restart();

            //    var result = StopSignDetectionModel.Predict(new StopSignDetectionModel.ModelInput()
            //    {
            //        ImageSource = file
            //    });

            //    sw.Stop();
            //    Console.WriteLine($"Prediction took {sw.Elapsed}ms.");
            //}
        }
    }
}
